---
local_env_vars:
  JENKINS_VERSION: 'jenkins_2.89.4'
  CONTAINER_NAME: 'jenkins'
  JENKINS_WAR_SOURCE: 'https://s3.amazonaws.com/edx-testeng-tools/jenkins'
  CONFIG_PATH: 'test_data'
  PLUGIN_CONFIG: 'test_data/plugins.yml'
  LC_ALL: 'C'

repo_dir: "{{ user_dir }}/jenkins-configuration/"

# hub.docker.com credentials
docker_id: ''
docker_pass: ''
