---

- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - { role: docker, tags: ['docker'] }
    - { role: java-openjdk, tags: ['java'] }
    - { role: gradle, tags: ['gradle'] }
    - { role: git_clone, tags: ['git_clone'] }
    - { role: jenkins, tags: ['jenkins'] }
