---
- name: Install unzip
  apt:
    pkg: unzip
    state: present

- name: Check that the gradle folder exists
  stat:
    path: "/opt/gradle/{{ gradle_folder }}"
  register: gradle_folder

- name: Install Gradle
  include_tasks: "install.yml"
  when: gradle_folder.stat.exists == false
  become: yes
