---
- name: Install unzip
  apt:
    pkg: unzip
    state: present

- name: Check that the gradle folder exists
  stat:
    path: "{{ gradle_folder }}"
  register: gradle_folder_test

- name: Install Gradle
  include: "install.yml"
  become: yes
  when: not gradle_folder_test.stat.exists
