docker_common_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - cron

docker_gpg_key_url: "https://download.docker.com/linux/ubuntu/gpg"
docker_repository: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
