---
- name: Make clean
  shell: make clean
  args: 
    chdir: "{{ repo_dir }}"
  environment: "{{ local_env_vars }}"

- name: Make requirements 
  shell: make requirements
  args: 
    chdir: "{{ repo_dir }}"
  environment: "{{ local_env_vars }}"

- name: Make plugins 
  shell: make plugins
  args: 
    chdir: "{{ repo_dir }}"
  environment: "{{ local_env_vars }}"

- name: Log into DockerHub
  docker_login:
    username: "{{ docker_id }}"
    password: "{{ docker_pass }}"

- name: Build a dockerfile
  shell: make build
  args: 
    chdir: "{{ repo_dir }}"
  environment: "{{ local_env_vars }}"

- name: Run Docker container
  shell: make run.container
  args: 
    chdir: "{{ repo_dir }}"
  environment: "{{ local_env_vars }}"

- name: Run Jenkins
  shell: make run.jenkins
  args: 
    chdir: "{{ repo_dir }}"
  environment: "{{ local_env_vars }}"

- name: Create network
  shell: docker network create -d bridge net

- name: Connect jenkins to workers network
  shell: docker network connect net jenkins

- name: Run workers
  shell: "docker-compose -f docker-compose.yml up -d  --scale worker={{ workers_number }}"
  args: 
    chdir: "{{ repo_dir }}"
