---
- name: Make clean
  shell: make clean
  args: 
    chdir: "{{ repo_dir }}"
  environment: "{{ local_env_vars }}"

- name: Make requirements 
  shell: make requirements
  args: 
    chdir: "{{ repo_dir }}"
  environment: "{{ local_env_vars }}"

- name: Make plugins 
  shell: make plugins
  args: 
    chdir: "{{ repo_dir }}"
  environment: "{{ local_env_vars }}"

- name: Log into DockerHub
  docker_login:
    username: "{{ docker_id }}"
    password: "{{ docker_pass }}"

- name: Build a dockerfile
  shell: make build
  args: 
    chdir: "{{ repo_dir }}"
  environment: "{{ local_env_vars }}"

- name: Run Docker container
  shell: make run.container
  args: 
    chdir: "{{ repo_dir }}"
  environment: "{{ local_env_vars }}"

- name: Run Jenkins
  shell: make run.jenkins
  args: 
    chdir: "{{ repo_dir }}"
  environment: "{{ local_env_vars }}"
