---
- name: Install pip
  apt:
    name: python-pip
    update_cache: yes
  become: yes

- name: Install docker-py
  pip:
    name: docker-py
  become: yes

- name: Install edX tests jenkins
  include: "edx-jenkins.yml"
  become: yes
  become_user: "{{ jenkins_user }}"
